### ISSUE TITLE
Trouble with OAuth Token

### ISSUE THREAD

**Issue by whalesunGC** [hermanho/MMM-OneDrive#1]
having trouble with OAuth Token Step

my steps
1) cloned repo
2) cd to MMM-OneDrive
3) npm install
4) cd MagicMirror
5) npm run start

this is the output i got

(Use `electron --trace-warnings ...` to show where the warning was created)
[26.01.2024 06:55.39.337] [ERROR] (node:20548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a 
promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

Am i doing something wrong?

**Comment by hermanho** [comment]
Is there a new tab page / browser opened in the background?

**Comment by whalesunGC** [comment]
Unfortunately not. Just the error message.On 26 Jan 2024, at 6:30 PM, Herman Ho ***@***.***> wrote:﻿
Is there a new tab page / browser opened in the background?

**Comment by hermanho** [comment]
Could you please the environment detail like OS, nodejs version, MagicMirror version?

**Comment by whalesunGC** [comment]
Yes you’re right I should have provided thatOS : Windows 10 and Debian BusterNodeJS: 20.11LTSMagicMirror: 2.26.0Warmest Regards,Wilson On 26 Jan 2024, at 7:38 PM, Herman Ho ***@***.***> wrote:﻿
Could you please the environment detail like OS, nodejs version, MagicMirror version?

**Comment by hermanho** [comment]
I fixed a bug in the code repo. Please pull the latest one from the repo and see if it works.

**Comment by whalesunGC** [comment]
I recreated my Debian Buster VM and went thru the installation steps.

1) Installed a working MagicMirror tested.
2) git clone MMM-OneDrive
3) on npm install setup a new error popped up.

400 verbose stack Error: command failed
400 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
400 verbose stack     at ChildProcess.emit (node:events:518:28)
400 verbose stack     at maybeClose (node:internal/child_process:1105:16)
400 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
401 verbose pkgid lzma-native@8.0.6
402 verbose cwd /home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive
403 verbose Linux 4.19.157-perf-26272441-abT500XXS6CWI2
404 verbose node v20.11.0
405 verbose npm  v10.2.4
406 error code 1
407 error path /home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native
408 error command failed
409 error command sh -c node-gyp-build
410 error gyp info it worked if it ends with ok
410 error gyp info using node-gyp@9.4.0
410 error gyp info using node@20.11.0 | linux | arm64
410 error gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
410 error gyp info spawn /usr/bin/python3
410 error gyp info spawn args [
410 error gyp info spawn args   '/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/node-gyp/gyp/gyp_main.py',
410 error gyp info spawn args   'binding.gyp',
410 error gyp info spawn args   '-f',
410 error gyp info spawn args   'make',
410 error gyp info spawn args   '-I',
410 error gyp info spawn args   '/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native/build/config.gypi',
410 error gyp info spawn args   '-I',
410 error gyp info spawn args   '/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/node-gyp/addon.gypi',
410 error gyp info spawn args   '-I',
410 error gyp info spawn args   '/root/.cache/node-gyp/20.11.0/include/node/common.gypi',
410 error gyp info spawn args   '-Dlibrary=shared_library',
410 error gyp info spawn args   '-Dvisibility=default',
410 error gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/20.11.0',
410 error gyp info spawn args   '-Dnode_gyp_dir=/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/node-gyp',
410 error gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/20.11.0/<(target_arch)/node.lib',
410 error gyp info spawn args   '-Dmodule_root_dir=/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native',
410 error gyp info spawn args   '-Dnode_engine=v8',
410 error gyp info spawn args   '--depth=.',
410 error gyp info spawn args   '--no-parallel',
410 error gyp info spawn args   '--generator-output',
410 error gyp info spawn args   'build',
410 error gyp info spawn args   '-Goutput_dir=.'
410 error gyp info spawn args ]
410 error gyp: Call to 'sh liblzma-config.sh "/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native/build" "/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
410 error gyp ERR! configure error 
410 error gyp ERR! stack Error: `gyp` failed with exit code: 1
410 error gyp ERR! stack     at ChildProcess.onCpExit (/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/node-gyp/lib/configure.js:325:16)
410 error gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
410 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
410 error gyp ERR! System Linux 4.19.157-perf-26272441-abT500XXS6CWI2
410 error gyp ERR! command "/usr/bin/node" "/home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/.bin/node-gyp" "rebuild"
410 error gyp ERR! cwd /home/CheeFamCalPrime/MagicMirror/modules/MMM-OneDrive/node_modules/lzma-native
410 error gyp ERR! node -v v20.11.0
410 error gyp ERR! node-gyp -v v9.4.0
410 error gyp ERR! not ok
411 verbose exit 1
412 timing npm Completed in 24816ms
413 verbose unfinished npm timer reify 1706318876449
414 verbose unfinished npm timer reify:build 1706318893187
415 verbose unfinished npm timer build 1706318893193
416 verbose unfinished npm timer build:deps 1706318893195
417 verbose unfinished npm timer build:run:install 1706318893394
418 verbose unfinished npm timer build:run:install:node_modules/lzma-native 1706318893395
419 verbose code 1

**Comment by hermanho** [comment]
In the step 3, please execute `npm run install-prod`

**Comment by whalesunGC** [comment]
Thanks Herman!Installed and works now!Let me know when you come to SG will buy you a 🍺🍺🍺On 27 Jan 2024, at 9:58 AM, Herman Ho ***@***.***> wrote:﻿
In the step 3, please execute npm run install-prod

**Comment by hermanho** [comment]
Thank you for installing this module. I hope I will go sightseeing in SG 🇸🇬. It is a great country.
